# generated by datamodel-codegen:
#   filename:  schemas
#   source:    scripts/generate_models.py

from __future__ import annotations

from datetime import date

try:
    from enum import StrEnum
except ImportError:  # Python 3.10 compatibility
    from enum import Enum

    class StrEnum(str, Enum):
        pass
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Corridor(StrEnum):
    hormuz = 'HORMUZ'
    bab_el_mandeb = 'BAB_EL_MANDEB'
    malacca = 'MALACCA'
    other = 'OTHER'
class PercentileBand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    p10: float = Field(..., description='10th percentile')
    p50: float = Field(..., description='50th percentile (median)')
    p90: float = Field(..., description='90th percentile')
class ForecastTrajectoryStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forecast_date: date
    score_band: PercentileBand
class EventType(StrEnum):
    military = 'MILITARY'
    sanction = 'SANCTION'
    accident = 'ACCIDENT'
    piracy = 'PIRACY'
    diplomatic = 'DIPLOMATIC'
    infrastructure = 'INFRASTRUCTURE'
    unknown = 'UNKNOWN'


class SignalEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: UUID = Field(..., description='Unique event identifier')
    corridor: Corridor
    event_type: EventType
    severity: float = Field(..., ge=0.0, le=1.0)
    goldstein_scale: float = Field(
        ..., description='Raw GDELT Goldstein scale value', ge=-10.0, le=10.0
    )
    confidence: float = Field(
        ..., description='Extraction model confidence', ge=0.0, le=1.0
    )
    event_date: date = Field(..., description='ISO 8601 date')
    ingested_at: AwareDatetime = Field(..., description='ISO 8601 datetime, UTC')
    source_url: AnyUrl
    raw_text_snippet: str = Field(
        ..., description='Audit snippet, max 500 chars', max_length=500
    )
class Trend7d(StrEnum):
    rising = 'RISING'
    falling = 'FALLING'
    stable = 'STABLE'


class RiskScore(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    corridor: Corridor
    score: float = Field(..., ge=0.0, le=1.0)
    score_date: date = Field(..., description='ISO 8601 date')
    contributing_event_ids: list[UUID]
    trend_7d: Trend7d
class CascadeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scenario_id: UUID
    corridor: Corridor
    disruption_duration_days: int = Field(..., ge=0)
    n_simulations: int = Field(..., ge=1)
    price_impact_pct: PercentileBand
    refinery_throughput_impact_pct: PercentileBand
    spr_days_required: PercentileBand
    affected_downstream_nodes: list[str]
class NodeType(StrEnum):
    production_field = 'PRODUCTION_FIELD'
    corridor = 'CORRIDOR'
    port = 'PORT'
    refinery = 'REFINERY'
    demand_center = 'DEMAND_CENTER'


class GraphNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: str
    node_type: NodeType
    name: str
    lat: float
    lon: float
    capacity_mbpd: float = Field(..., ge=0.0)
class GraphEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., description='Source node_id')
    target: str = Field(..., description='Target node_id')
    flow_mbpd: float = Field(..., ge=0.0)
    corridor_dependency: Corridor
    alt_route_penalty_days: float = Field(..., ge=0.0)
class Option(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    option_id: str
    description: str
    cost_score: float = Field(..., description='Lower is better', ge=0.0, le=1.0)
    time_score: float = Field(..., description='Lower is better', ge=0.0, le=1.0)
    risk_score: float = Field(..., description='Lower is better', ge=0.0, le=1.0)
    is_pareto_optimal: bool


class Status(StrEnum):
    pending_approval = 'PENDING_APPROVAL'
    approved = 'APPROVED'
    rejected = 'REJECTED'
    expired = 'EXPIRED'
    no_feasible_option = 'NO_FEASIBLE_OPTION'


class Recommendation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    recommendation_id: UUID
    generated_at: AwareDatetime = Field(..., description='ISO 8601 datetime')
    trigger_corridor: Corridor
    source_cascade_id: UUID = Field(
        ..., description='CascadeResult scenario that triggered this recommendation'
    )
    source_forecast_id: UUID | None = Field(
        None, description='Optional RiskForecast that informed corridor selection'
    )
    inputs_as_of: AwareDatetime = Field(
        ..., description='Timestamp of upstream inputs used for generation'
    )
    options: list[Option]
    status: Status
    operator_note: str | None
class ModelSource(StrEnum):
    gru = 'GRU'
    trend_fallback = 'TREND_FALLBACK'


class RiskForecast(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forecast_id: UUID
    corridor: Corridor
    origin_date: date = Field(
        ..., description='Last observed score date used as forecast origin'
    )
    horizon_days: int = Field(..., ge=1, le=7)
    model_source: ModelSource
    training_data_through: date = Field(
        ...,
        description='Last calendar date used to fit GRU weights (train partition cutoff)',
    )
    feature_data_through: date = Field(
        ...,
        description='Last observed feature/score date used as forecast origin (matches origin_date)',
    )
    trajectory: list[ForecastTrajectoryStep] = Field(
        ..., max_length=7, min_length=1
    )
