/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
 * Source: /schemas/*.json (SETU SRS Section 6)
 */

export type Corridor = "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";

export interface PercentileBand {
  p10: number;
  p50: number;
  p90: number;
}

export interface SignalEvent {
  event_id: string;
  corridor: "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";
  event_type: "MILITARY" | "SANCTION" | "ACCIDENT" | "PIRACY" | "DIPLOMATIC" | "INFRASTRUCTURE" | "UNKNOWN";
  severity: number;
  goldstein_scale: number;
  confidence: number;
  event_date: string;
  ingested_at: string;
  source_url: string;
  raw_text_snippet: string;
}

export interface RiskScore {
  corridor: "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";
  score: number;
  score_date: string;
  contributing_event_ids: string[];
  trend_7d: "RISING" | "FALLING" | "STABLE";
}

export interface CascadeResult {
  scenario_id: string;
  corridor: "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";
  disruption_duration_days: number;
  n_simulations: number;
  price_impact_pct: CascadeResultPriceImpactPct;
  refinery_throughput_impact_pct: CascadeResultRefineryThroughputImpactPct;
  spr_days_required: CascadeResultSprDaysRequired;
  affected_downstream_nodes: string[];
}

export interface GraphNode {
  node_id: string;
  node_type: "PRODUCTION_FIELD" | "CORRIDOR" | "PORT" | "REFINERY" | "DEMAND_CENTER";
  name: string;
  lat: number;
  lon: number;
  capacity_mbpd: number;
}

export interface GraphEdge {
  source: string;
  target: string;
  flow_mbpd: number;
  corridor_dependency: "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";
  alt_route_penalty_days: number;
}

export interface Recommendation {
  recommendation_id: string;
  generated_at: string;
  trigger_corridor: "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";
  options: Record<string, unknown>[];
  status: "PENDING_APPROVAL" | "APPROVED" | "REJECTED" | "EXPIRED";
  operator_note: string | null;
}

export interface RecommendationOption {
  option_id: string;
  description: string;
  cost_score: number;
  time_score: number;
  risk_score: number;
  is_pareto_optimal: boolean;
}
