#!/usr/bin/env python3
"""Generate Pydantic models and TypeScript types from JSON schemas in /schemas/."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = ROOT / "schemas"
BACKEND_OUT = ROOT / "backend" / "app" / "models" / "generated.py"
FRONTEND_OUT = ROOT / "frontend" / "src" / "types" / "generated.ts"

CONTRACT_SCHEMAS = [
    "signal_event.json",
    "risk_score.json",
    "cascade_result.json",
    "graph_node.json",
    "graph_edge.json",
    "recommendation.json",
]

# Order matters for shared types before dependents
MERGE_ORDER = [
    "corridor.py",
    "percentile_band.py",
    "signal_event.py",
    "risk_score.py",
    "cascade_result.py",
    "graph_node.py",
    "graph_edge.py",
    "recommendation.py",
]


def generate_pydantic() -> None:
    """Generate Pydantic models via datamodel-code-generator into a single file."""
    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        cmd = [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(SCHEMAS_DIR),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(out_dir),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--use-standard-collections",
            "--use-union-operator",
            "--field-constraints",
            "--snake-case-field",
            "--disable-timestamp",
            "--target-python-version",
            "3.11",
        ]
        print("Running:", " ".join(cmd))
        subprocess.run(cmd, check=True, cwd=ROOT)

        merged = _merge_generated_modules(out_dir)
        BACKEND_OUT.write_text(merged, encoding="utf-8")
        print(f"Wrote {BACKEND_OUT}")


def _merge_generated_modules(out_dir: Path) -> str:
    """Combine modular codegen output into one importable module."""
    body_parts: list[str] = []

    for filename in MERGE_ORDER:
        path = out_dir / filename
        if not path.exists():
            continue
        content = path.read_text(encoding="utf-8")
        content = re.sub(r"^# generated by datamodel-codegen:.*\n(?:#.*\n)*", "", content)
        content = re.sub(r"from \. import \w+.*\n", "", content)
        content = re.sub(r"from \.[\w]+ import \w+.*\n", "", content)
        content = re.sub(r"^from __future__ import annotations\n", "", content)
        content = content.replace("corridor_1.Corridor", "Corridor")
        content = content.replace("percentile_band_1.PercentileBand", "PercentileBand")
        content = content.replace("corridor.Corridor", "Corridor")
        content = content.replace("percentile_band.PercentileBand", "PercentileBand")

        lines = content.splitlines()
        body: list[str] = []
        for line in lines:
            if line.startswith("from ") or line.startswith("import "):
                continue
            body.append(line)

        body_parts.append("\n".join(body).strip())

    header = [
        "# generated by datamodel-codegen:",
        "#   filename:  schemas",
        "#   source:    scripts/generate_models.py",
        "",
        "from __future__ import annotations",
        "",
        "from datetime import date",
        "from enum import StrEnum",
        "from uuid import UUID",
        "",
        "from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field",
        "",
    ]
    return "\n".join(header + body_parts) + "\n"


REF_TYPE_MAP = {
    "corridor.json": "Corridor",
    "percentile_band.json": "PercentileBand",
}


def _ref_type_name(ref_path: str) -> str | None:
    return REF_TYPE_MAP.get(Path(ref_path).name)


def _resolve_ref(schema: dict, root: Path) -> dict:
    if "$ref" in schema:
        ref_path = schema["$ref"]
        if not ref_path.startswith("#"):
            ref_file = root / ref_path
            with ref_file.open() as f:
                resolved = json.load(f)
            return _resolve_refs_deep(resolved, root)
    return schema


def _resolve_refs_deep(obj: object, root: Path) -> object:
    if isinstance(obj, dict):
        if "$ref" in obj and len(obj) == 1:
            return _resolve_ref(obj, root)
        return {k: _resolve_refs_deep(v, root) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_resolve_refs_deep(i, root) for i in obj]
    return obj


def _ts_type(
    schema: dict,
    root: Path,
    name_hint: str = "",
    *,
    array_item_name: str | None = None,
) -> str:
    if "$ref" in schema:
        mapped = _ref_type_name(schema["$ref"])
        if mapped:
            return mapped
        schema = _resolve_ref(schema, root)

    if "enum" in schema:
        return " | ".join(f'"{v}"' for v in schema["enum"])

    schema_type = schema.get("type")

    if schema_type == "string":
        return "string"

    if schema_type in ("number", "integer"):
        return "number"

    if schema_type == "boolean":
        return "boolean"

    if schema_type == "array":
        items = schema.get("items", {})
        if array_item_name:
            return f"{array_item_name}[]"
        if items.get("type") == "object" and "properties" in items:
            return f"{name_hint}Item[]" if name_hint else "Record<string, unknown>[]"
        return f"{_ts_type(items, root)}[]"

    if schema_type == "object":
        return name_hint or "Record<string, unknown>"

    if isinstance(schema.get("type"), list):
        parts = []
        for t in schema["type"]:
            if t == "null":
                parts.append("null")
            else:
                parts.append(_ts_type({"type": t}, root))
        return " | ".join(parts)

    return "unknown"


def _emit_interface(name: str, schema: dict, root: Path) -> str:
    schema = _resolve_refs_deep(schema, root)
    lines = [f"export interface {name} {{"]

    props = schema.get("properties", {})
    required = set(schema.get("required", []))

    for prop_name, prop_schema in props.items():
        prop_schema = _resolve_refs_deep(prop_schema, root)
        optional = "" if prop_name in required else "?"
        ts: str

        if prop_name == "options" and name == "Recommendation":
            ts = "RecommendationOption[]"
        elif prop_name in (
            "price_impact_pct",
            "refinery_throughput_impact_pct",
            "spr_days_required",
        ):
            ts = "PercentileBand"
        elif prop_name in ("corridor", "trigger_corridor", "corridor_dependency"):
            ts = "Corridor"
        elif prop_name == "operator_note" and prop_schema.get("type") == ["string", "null"]:
            ts = "string | null"
        elif prop_schema.get("type") == "object" and "properties" in prop_schema:
            nested_name = f"{name}{_to_pascal(prop_name)}"
            ts = nested_name
        else:
            ts = _ts_type(prop_schema, root, _to_pascal(prop_name))

        lines.append(f"  {prop_name}{optional}: {ts};")

    lines.append("}")
    return "\n".join(lines)


def _to_pascal(s: str) -> str:
    return "".join(part.capitalize() for part in s.replace("-", "_").split("_"))


def generate_typescript_python() -> None:
    FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)

    parts = [
        "/* eslint-disable */",
        "/**",
        " * AUTO-GENERATED by scripts/generate_models.py — do not edit manually.",
        " * Source: /schemas/*.json (SETU SRS Section 6)",
        " */",
        "",
        'export type Corridor = "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";',
        "",
        "export interface PercentileBand {",
        "  p10: number;",
        "  p50: number;",
        "  p90: number;",
        "}",
        "",
    ]

    title_map = {
        "signal_event.json": "SignalEvent",
        "risk_score.json": "RiskScore",
        "cascade_result.json": "CascadeResult",
        "graph_node.json": "GraphNode",
        "graph_edge.json": "GraphEdge",
        "recommendation.json": "Recommendation",
    }

    for filename in CONTRACT_SCHEMAS:
        path = SCHEMAS_DIR / filename
        with path.open() as f:
            schema = json.load(f)
        name = title_map[filename]
        parts.append(_emit_interface(name, schema, SCHEMAS_DIR))
        parts.append("")

        if filename == "recommendation.json":
            opts = schema["properties"]["options"]["items"]
            parts.append(_emit_interface("RecommendationOption", opts, SCHEMAS_DIR))
            parts.append("")

    FRONTEND_OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {FRONTEND_OUT}")


def try_npx_typescript() -> bool:
    FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    try:
        chunks = [
            "/* AUTO-GENERATED via json-schema-to-typescript */\n",
            'export type Corridor = "HORMUZ" | "BAB_EL_MANDEB" | "MALACCA" | "OTHER";\n\n',
        ]
        for filename in CONTRACT_SCHEMAS:
            schema_path = SCHEMAS_DIR / filename
            result = subprocess.run(
                ["npx", "--yes", "json-schema-to-typescript", str(schema_path)],
                capture_output=True,
                text=True,
                cwd=ROOT,
                timeout=120,
            )
            if result.returncode != 0:
                print(f"npx failed for {filename}: {result.stderr}")
                return False
            chunks.append(result.stdout)
            chunks.append("\n")

        FRONTEND_OUT.write_text("".join(chunks), encoding="utf-8")
        print(f"Wrote {FRONTEND_OUT} (via npx)")
        return True
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        print(f"npx unavailable: {exc}")
        return False


def main() -> None:
    generate_pydantic()
    if not try_npx_typescript():
        print("Falling back to Python TypeScript emitter...")
        generate_typescript_python()


if __name__ == "__main__":
    main()
